name = "domain-a-tools-worker"
type = "service"
main = "dist/index.js"
compatibility_date = "2024-12-01"

[env.development]
name = "domain-a-tools-worker-dev"
routes = [
  { pattern = "localhost:8001/*", zone_name = "local" }
]

[env.production]
name = "domain-a-tools-worker"
routes = []

[env.production.vars]
ENVIRONMENT = "production"
DOMAIN_SHARED_SECRET = "prod-secret-123"

[build]
command = "npm run build"

[[env.development.services]]
binding = "ENVIRONMENT"
service = "domain-a-tools-worker-dev"

[vars]
ENVIRONMENT = "development"
